on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: 'stable'
          architecture: x64
      - name: Get depedencies
        run: flutter analyze
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to codecov
        run: curl -Os https://uploader.codecov.io/latest/macos/codecov chmod +x codecov ./codecov
        shell: bash
      - name: Build Android
        run: flutter build apk --debug --split-per-abi
      - name: Build Android App Bundle
        run: flutter build appbundle
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.PAT }}
          commit: ${{ github.sha }}
          tag: ${{ steps.version.outputs.content }}